# Generated by Django 4.1.7 on 2023-02-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название теста')),
                ('max_points', models.PositiveSmallIntegerField(verbose_name='Максимальное количество баллов')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(verbose_name='Количество баллов')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата сдачи теста')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course', verbose_name='Тест')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(verbose_name='Количество баллов за правильный ответ')),
                ('name', models.CharField(max_length=500, verbose_name='Содержание вопроса')),
                ('option_a', models.CharField(max_length=200, verbose_name='Вариант ответа А')),
                ('option_b', models.CharField(max_length=200, verbose_name='Вариант ответа B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Вариант ответа C')),
                ('option_d', models.CharField(max_length=200, verbose_name='Вариант ответа D')),
                ('option_e', models.CharField(max_length=200, verbose_name='Вариант ответа E')),
                ('answer', models.CharField(choices=[('OptionA', 'OptionA'), ('OptionB', 'OptionB'), ('OptionC', 'OptionC'), ('OptionD', 'OptionD'), ('OptionE', 'OptionE')], max_length=200, verbose_name='Правильный ответ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
